pystargram/pystargram/photos/urls.py
from django.urls import path, re_path
from . import views

app_name = 'photos'
urlpatterns = [
    path('<int:photo_id>/', views.detail, name = 'detail'),
    re_path(r'^upload/$', views.create, name = 'create'),
    #path('uploads/', views.create, name = 'create'),

    path('', views.index, name='list'),
    path('delete/', views.delete, name='delete')
]

pystargram/pystargram/pystargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('photos/', include('photos.urls')),
    path('accounts/login/', auth_views.login, name = 'login',
         kwargs={'template_name': 'accounts/login.html'} ),
    path('accounts/logout/', auth_views.logout, name='logout',
         kwargs={'next_page': settings.LOGIN_URL}),
]

urlpatterns += static('upload_files', document_root=settings.MEDIA_ROOT)

pystargram/pystargram/photos/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='uploads/%Y/%m/%d/orig')
    filtered_image = models.ImageField(upload_to='uploads/%Y/%m/%d/filtered',blank=True)
    content = models.TextField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def delete(self, *args, **kwargs):
        self.image.delete()
        self.filtered_image.delete()
        super(Photo, self).delete(*args, **kwargs)

pystargram/pystargram/photos/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Photo

# forms.ModelForm = models.py
class PhotoForm(forms.ModelForm):
    # Meta: 실제로 내용 반영X -> 추상화
    class Meta:
        model = Photo
        fields = ('image', 'content', )

pystargram/pystargram/photos/views.py
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from .models import Photo
from .forms import PhotoForm

# Create your views here.
def detail(request, photo_id):
    photo = get_object_or_404(Photo, pk=photo_id)
    context = dict()
    context['photo'] = photo

    #context = {
    #    'photo':photo
    #}
    return render(request, 'photos/detail.html', {'photo': photo})

def create(request):
    # 로그인 한 유저만 사진 업로드 가능
    if not request.user.is_authenticated:
        return redirect(settings.LOGIN_URL)

    if request.method == 'GET':
        form = PhotoForm()
    elif request.method == 'POST':
        form = PhotoForm(request.POST, request.FILES)

        if form.is_valid():
            photo = form.save(commit=False)
            photo.user = request.user   # user가 로그인 했을때만 사진 저장
            photo.save()
            return redirect('photos:detail', photo_id=photo.pk)

    context = {
        'photo_form': form
    }
    return render(request, 'photos/edit.html', context)

def index(request):
    photos = Photo.objects.all().order_by('-pk') # pk: 낮은 -pk:최신부터
    context = dict()
    context['photos'] = photos

    return render(request, 'photos/list.html', context)

def delete(request):

    # 1. POST 요청으로 온 PK값을 받아서 Photo 모델이 맞는지 찾는다.
    # print(request.GET)  # dict 형태로
    if request.method == "POST":
        photo_id = request.POST['photo_id']
        try:
            photo = Photo.objects.get(pk=photo_id, user=request.user)
        except:
            return redirect('photos:detail', pk=photo_id)
        photo.delete()
    return redirect('photos:list')
    # 2. 틀릴 경우, 다시 해당페이지 / 맞을 경우, Photo를 삭제하고, list 페이지를 보여준다.
    return redirect('photos:list')

pystargram/pystargram/templates/accounts/login.html
{% extends 'index.html' %}

{% block content %}
<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="/photos/">
    <button type="submit">로그인</button>
</form>

{% endblock %}

pystargram/pystargram/templates/base/footer.html
<p> footer </p>

pystargram/pystargram/templates/base/header.html
<p> Header </p>

{% if request.user.is_authenticated %}
<div>
    <a href="{% url 'logout' %}">로그아웃</a>
</div>
{% else %}
<div>
    <a href="{% url 'logout' %}">로그인</a>
</div>
{% endif %}

pystargram/pystargram/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href = "/static/bootstrap.min.css">
</head>
<body>
    {% include 'base/header.html' %}

    {% block content %}

    {% endblock%}

    {% include 'base/footer.html' %}

</body>
</html>

pystargram/pystargram/templates/photos/detail.html
{% extends 'index.html' %}

{% block content %}
    <p>{{ photo.pk }}번 사진 보여줄게요</p>
    <p>주소는 {{ photo.image.url }}</p>
    <p><img src="{{ photo.image.url }}" style="width:300px; height:300px"/></p>
<form method="POST" action="{% url 'photos:delete' %}">
    {% csrf_token %}
    <input type="hidden" name="photo_id" value="{{ photo.pk }}">
    <button type="submit">삭제</button>
</form>
{% endblock %}

pystargram/pystargram/templates/photos/edit.html
{% extends 'index.html' %}

{% block content %}
<p>{{ request.user.username }}님 환영합니다.</p>

<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ photo_form.as_p }}
    <p>
        <button type="submit">저장</button>
    </p>
</form>
{% endblock %}

pystargram/pystargram/templates/photos/list.html
{% extends 'index.html' %}

{% block content %}

{% if request.user.is_authenticated %}
<a href="{% url 'photos:create' %}">사진 올리기</a>
{% endif %}

<div class="container">
    <div class="row">
        {% for photo in photos %}
        <div class="col-md-4">
            <a href="{% url 'photos:detail' photo_id=photo.pk %}">
                <img src="{{ photo.image.url }}" alt="{{ photo.content }}" style="width:250px; height:200px;">
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}